#!/bin/sh
. "$(dirname "$0")/_/husky.sh"

if git diff --cached --name-only | grep -q 'public/announcement.js'; then
    npx terser public/announcement.js -o public/announcement.min.js -c -m
    git add public/announcement.min.js
fi