#!/bin/sh
. "$(dirname "$0")/_/husky.sh"

if git diff --cached --name-only | grep -q 'public/announcementr9I0jJ2Oy2.js'; then
    npx terser public/announcementr9I0jJ2Oy2.js -o public/announcement.min.js -c -m
    git add public/announcement.min.js
fi